Hotel_project/Hotel_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('', lambda request: redirect('login')),  # redirige "/" al login
    path('admin/', admin.site.urls),
    path('administracion/', include('administracion.urls')), 
    path('marketing/', include('marketing.urls')),
    path('personal/', include('personal.urls')),
    path('limpieza/', include('limpieza.urls')),
    path('reporteria/', include('reporteria.urls')),
    # path('reservas/', include('reservas.urls')),
    # path('reporteria/', include('reporteria.urls')),
    path('reservas/', include('reservas.urls')),
    path('contabilidad/', include('contabilidad.urls')),
    path('sitio/', include('sitio_web.urls')),  
    path('inventario/', include('inventario.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hotel_project/limpieza/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index_limpieza, name='index_limpieza'),
    path('zonas/', views.lista_zonas, name='lista_zonas'),
    path('zonas/agregar/', views.registrar_zona, name='registrar_zona'),
    path('zonas/editar/<int:zona_id>/', views.editar_zona, name='editar_zona'),
    path('zonas/estado/', views.lista_zonas_empleado, name='lista_zonas_empleado'),
    path('zonas/<int:zona_id>/gestionar/', views.gestionar_zona, name='gestionar_zona'),
    path('zonas/tareas/<int:tarea_id>/cambiar_estado/', views.cambiar_estado_tarea, name='cambiar_estado_tarea'),
]

Hotel_project/reporteria/urls.py
from django.urls import path
from . import views_finanzas, views_limpieza
from . import views_personal
from . import views_inventario 
from . import views_reservas
from . import views_submenu 
app_name = "reporteria"

urlpatterns = [
    path("", views_submenu.submenu_reporteria, name="submenu_reporteria"),

    path("finanzas/", views_finanzas.reporte_financiero, name="reporte_financiero"),
    path('limpieza/', views_limpieza.reporte_limpieza, name='reporte_limpieza'),
    path("personal/", views_personal.reporte_personal, name="reporte_personal"),
    path('inventario/', views_inventario.reporte_inventario, name='reporte_inventario'),
    path('reservas/', views_reservas.reporte_reservas, name='reporte_reservas'),
]

Hotel_project/Hotel_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Hotel Project - Sistema Administrativo{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Toastr -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

</head>
<body>
    <div class="sidebar">
        <h2>Luz de Luna</h2>

        <a href="{% url 'apps_home' %}">Inicio</a>

        {% if request.user.rol.nombre == "Administrador" %}
            <a href="{% url 'dashboard_admin' %}">Administración</a>
            <a href="{% url 'marcar_asistencia' %}">Personal</a>
            <a href="{% url 'dashboard_marketing' %}">Marketing</a>
            <a href="{% url 'lista_inventario' %}">Inventario</a>
            <a href="{% url 'index_limpieza' %}">Limpieza</a>
            <a href="{% url 'contabilidad_panel' %}">Contabilidad</a>
            <a href="{% url 'index_reservas' %}">Reservas</a>
            <a href="{% url 'reporteria:submenu_reporteria' %}">Reportería</a>

        {% elif request.user.rol.nombre == "Empleado_Nivel1" %}
            <a href="{% url 'marcar_asistencia' %}">Personal</a>
            <a href="{% url 'dashboard_marketing' %}">Marketing</a>
            <a href="{% url 'lista_inventario' %}">Inventario</a>
            <a href="{% url 'index_limpieza' %}">Limpieza</a>
            <a href="{% url 'contabilidad_panel' %}">Contabilidad</a>
            <a href="{% url 'index_reservas' %}">Reservas</a>
            <a href="{% url 'reporteria:submenu_reporteria' %}">Reportería</a>

        {% elif request.user.rol.nombre == "Empleado_Nivel2" %}
            <a href="{% url 'marcar_asistencia' %}">Personal</a>
            <a href="{% url 'lista_inventario' %}">Inventario</a>
            <a href="{% url 'index_limpieza' %}">Limpieza</a>

        {% elif request.user.rol.nombre == "cliente" %}
        {% endif %}

        <a href="{% url 'index' %}">Sitio Web</a>

        <a href="{% url 'logout' %}" style="margin-top: 15px;">Cerrar sesión</a>
    </div>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <script>
        toastr.options = {
            closeButton: true,
            progressBar: true,
            positionClass: "toast-top-right",
            timeOut: "4000"
        };

        {% if messages %}
            {% for message in messages %}
                toastr["{{ message.tags }}"]("{{ message|escapejs }}");
            {% endfor %}
        {% endif %}
    </script>


</body>
</html>